### PR TITLE
Update libraries and load them from cdn

### PR DESCRIPTION
**Pull request by curbengh**
Upgrade to (as of this PR)
* jquery 3.3.1
* clipboard.js 2.0.1
* fancybox 3.5.2
* html5shiv 3.7.3

Load following libraries from [jsDelivr](https://www.jsdelivr.com/) CDN (which claim to have good coverage in China):
* jquery
* clipboard.js
* fancybox
* html5shiv
* gitment
* valine
* fontawesome

Some syntax have been modified for compatibility with newer versions,
* `new Clipboard()` to `new ClipboardJS()` for clipboard.js 2.0+
* `fancybox` class to `data-fancybox` attribute and `title` to `data-caption` attribute for fancybox 3.0+

[SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) attribute is considered, but not implemented because version range is used (instead of a specific version).

I created a github page with these commit https://weyusi.github.io/hexo-testing/

Edit: [Reason](https://github.com/geekplux/hexo-theme-typing/pull/28#issuecomment-428412864) of not updating fontawesome to v5.

### CODE REVIEW

**Comment by geekplux** [comment]
awesome contribution, LGTM except the scroll arrows of fancybox gallery.

may need following code?

```html
<a data-fancybox="gallery" href="big_1.jpg"><img src="small_1.jpg"></a>
```

**Comment by curbengh** [comment]
yeah, the `data-fancybox` attribute needs `gallery` as value.
jsDelivr also support version range `@3` which serves latest version of version 3.
This can help reducing library maintenance, instead of constantly updating the `<script src>` whenever there is a minor library update.

btw, don't mind the Utterances comment not showing. I'm trying (and failing) to move the library to CDN. This PR still use the [original](https://github.com/geekplux/hexo-theme-typing/pull/28/commits/e06b823791c194e9d01e47ef0f31f42a166e9167) Utterances link.

**Comment by geekplux** [comment]
I see, great thanks 👍
Now gallery fixed, it works well. So this PR may merge now? or until you finish the migration of Utterances.

**Comment by curbengh** [comment]
please merge if there is no issue. The migration and testing of Utterances will take a while and probably doesn't work. I'll create another PR if it works.

**Comment by curbengh** [comment]
Just in case someone suggest upgrading to fontawesome 5, I don't include it in this PR because it can be confusing to new users (of this theme).
v5 [separates](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4) the icon styles into 4 (`solid` and `brands` are free to use). In v5,
[footer.ejs](https://github.com/geekplux/hexo-theme-typing/blob/master/layout/_partial/footer.ejs#L22)
```html
<li><a href="<%= theme.links[key] %>"><span class="fa fa-<%= key %>"></span></a></li>
```
**only** display [solid](https://fontawesome.com/icons?s=solid) icons, whereas that same line in v4 (currently used in this theme) can display all icons.

To display brand icons, you need `fab-` prefix,
```html
<li><a href="<%= theme.links[key] %>"><span class="fa fab-<%= key %>"></span></a></li>
```
But having the above line means `fab-` also applies on solid icons, which is incorrect in v5.

A possible workaround is to separate the [theme.links](https://github.com/geekplux/hexo-theme-typing/blob/master/_config.yml#L40) to solid and brand icons,
```html
<li><a href="<%= theme.links.solid[key] %>"><span class="fa fa-<%= key %>"></span></a></li>
<li><a href="<%= theme.links.brands[key] %>"><span class="fa fab-<%= key %>"></span></a></li>
```

Otherwise, use only one style. So, keep this in mind if you want to use v5.

**Comment by geekplux** [comment]
@weyusi  thanks reminder. Use one style may be better, I think.

**Pull request merged**
