### PR TITLE
add gitment comment system

### PR DESCRIPTION
**Pull request by MienJustSaysToHer**
add [gitment](https://github.com/imsun/gitment) comment system
Here's an example: [https://www.heyuhuan.com/2017/08/13/lintcode-single-number/](https://www.heyuhuan.com/2017/08/13/lintcode-single-number/)

### CODE REVIEW

**Comment by geekplux** [comment]
This is the greatest improvement, I think, for the theme so far. Thank you very much!

**Comment by MienJustSaysToHer** [comment]
You are welcome!

@geekplux 你真是太客气了！我前端水平有限，只能做一点这种微小的工作。反而是我应该感谢你提供这么美的 Hexo 主题，这个主题也是我见过的 Hexo 主题中我觉得最好看的，哈哈~

**Comment by geekplux** [comment]
哈哈，我说的很客观，你就略微浮夸啦。不过这个评论功能真的很棒，我也马上用起来

**Comment by Mehran-Baghi** [comment]
Thank you @MienJustSaysToHer 
Great commit. Adding gitment support is a good idea.
🙌

**Comment by MienJustSaysToHer** [comment]
@Mehran-Baghi I also want to thank you for your contribution to this theme. The theme is really beautiful.

**Pull request merged**
