### PR TITLE
Added `@` sign for Nickname at index page.

### PR DESCRIPTION
**Pull request by WyattJia**
Added `@` sign for Nickname at index page.I think it will be more 'Internet'.

### CODE REVIEW

**Comment by geekplux** [comment]
I think it would better be modified in your `config.yml`, not general templates.

**Comment by WyattJia** [comment]
@geekplux Agree with your opinion. But I still have a suggestion，maybe the `<h1>nickname</h1>` element is more like a **title** of an article ,not like a person's **nickname**. So I want to add `@` sign for nickname, used to distinguish between **title** and **nickname**, because the `@` sign is most commonly used in email addresses and social media platform "handles"，https://en.wikipedia.org/wiki/At_sign . I hope this is useful.Anyway, thank you~

**Comment by geekplux** [comment]
OK, 😄  I just think this is an option not a feature. You totally can change it in your config file.

**Comment by WyattJia** [comment]
OK, I understand.It's just a suggestion.

**Pull request closed without merging**
